name: BanyaXP
version: 3.2
main: hu.banya.BanyaPlugin
api-version: "1.21"
description: Banyasz es favago szintrendszer, zonak, Vault penz es PlaceholderAPI
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  banya:
    description: Banyasz rendszer
    usage: /banya [mine|pvpmine|tool|setmine|setregion]
    aliases: [banyasz]
permissions:
  banya.admin:
    description: Admin parancsok es szintkovetelmeny kihagyasa
    default: op
